# .github/workflows/deploy-frontend.yml
name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GCP VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}       # зазвичай 22
          script: |
            # Зайдемо в домашню папку
            cd /home/${{ secrets.USERNAME }}

            # Якщо папки ще нема — клонюємо репо, інакше оновлюємо
            if [ ! -d "Moondreams" ]; then
              git clone https://github.com/vprotsenko-git/Moondreams.git
            else
              cd Moondreams
              git reset --hard
              git pull origin main
              cd ..
            fi

            # Перейдімо всередину і зберемо/перезапустимо контейнер
            cd Moondreams
            docker compose down || true
            docker compose up -d --build