# .github/workflows/deploy-frontend.yml
name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GCP VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # 1) Переходимо в домашню папку
            cd /home/${{ secrets.USERNAME }}

            # 2) Клон чи оновлення репо
            if [ ! -d "Moondreams" ]; then
              git clone https://github.com/vprotsenko-git/Moondreams.git
            else
              cd Moondreams
              git reset --hard
              git pull origin main
              cd ..
            fi

            # 3) Встановлюємо Docker Compose Plugin локально, якщо його ще немає
            if ! docker compose version >/dev/null 2>&1; then
              echo "Встановлюємо Docker Compose Plugin у ~/.docker/cli-plugins..."
              mkdir -p ~/.docker/cli-plugins
              curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
                -o ~/.docker/cli-plugins/docker-compose
              chmod +x ~/.docker/cli-plugins/docker-compose
            fi

            # 4) Переходимо в проект і перезапускаємо контейнери
            cd Moondreams
            docker compose down || true
            docker compose up -d --build